<?php

namespace AppBundle\Repository;

/**
 * borderStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class borderStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
