<?php

namespace AppBundle\Repository;

/**
 * PopUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopUpRepository extends \Doctrine\ORM\EntityRepository
{
}
