<?php

namespace AppBundle\Repository;

/**
 * PopUpPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopUpPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
